version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  websocket:
    container_name: websocket
    build: 
      context: ./ParlAI
      dockerfile: BlenderConfigDockerfile
    expose:
      - 35496
    ports:
      - 35496:35496

  server:
    restart: always
    container_name: server
    build: ./ParlAI
    expose:
      - 8080
    ports:
      - 8080:8080